import torch
from fiftyone.core.map.batcher import batch
from torch import nn
from typing import Dict, Any, Tuple, Literal, Optional, List
from architecture_modules.backbone import Backbone
from architecture_modules.region_proposer import RegionProposal, RegionProposalFilter
from utilities.model.model_utilities import assign_targets_to_anchors, batch_assign_targets_to_anchors
from utilities.tensor_utilities import print_tensor_shape


class Model(nn.Module):
    """
    Constructs the overall object detection model by combining the backbone,
    region proposal, enhancer, and detector modules based on the configuration.
    """

    def __init__(self, configuration: Dict[str, Any], mode: Literal["training", "inference"],
                 device: torch.device = None, dtype: torch.dtype = None) -> None:
        """
        Initializes the Model components.
        
        Args:
            configuration (Dict[str, Any]): The complete configuration dictionary for the experiment.
            mode (Literal["training", "inference"]): The execution mode of the model.
            device (torch.device): The device for parameter allocation.
            dtype (torch.dtype): The data type for parameter allocation.
        """
        super(Model, self).__init__()

        # Assign device, dtype, and mode globally for the model
        self.device = device
        self.dtype = dtype
        self.mode = mode

        # Get configuration for each component of our model
        self.data_configuration = configuration.get('Data')
        self.backbone_configuration = configuration.get('Backbone')
        self.anchors_configuration = configuration.get('Anchors')
        self.region_proposal_configuration = configuration.get('RegionProposal')

        # Get input image size
        self.input_image_size = self.data_configuration.get("image_settings").get("size")

        # Initialize the backbone feature extractor using the dedicated builder method
        self.backbone = self._build_backbone(backbone_configuration=self.backbone_configuration)

        # Initialize the region proposal dictionary (since we are using a Feature Pyramid Network Approach)
        self.region_proposer_dictionary = self._build_region_proposer_dictionary(
            backbone_configuration=self.backbone_configuration,
            anchors_configuration=self.anchors_configuration)

        # Initialize the region proposal filter to refine the raw proposals generated by the network
        self.region_proposal_filter = self._build_region_proposal_filter(
            region_proposal_configuration=self.region_proposal_configuration)

    def _build_backbone(self, backbone_configuration: Dict[str, Any]) -> Backbone:
        """
        Instantiates the Backbone module based on the provided configuration blueprint.
        
        This builder method neatly encapsulates the construction of the visual feature 
        extractor, passing along the global structural parameters (like image size, 
        device, and precision type).
        
        Args:
            backbone_configuration (Dict[str, Any]): Configuration dictating the backbone topology and hyperparameters.
            
        Returns:
            Backbone: The fully initialized and configured feature extractor network.
        """
        backbone = Backbone(input_channels=backbone_configuration.get("input_channels"),
                            convolutions=backbone_configuration.get("convolutions"),
                            modules=backbone_configuration.get("modules"),
                            last_max_pooling=backbone_configuration.get("last_max_pooling"),
                            normalization=backbone_configuration.get("normalization"),
                            enhancer_convolution_indices=backbone_configuration.get("enhancer_convolution_indices"),
                            input_image_size=self.input_image_size,
                            device=self.device,
                            dtype=self.dtype)

        return backbone

    def _build_region_proposer_dictionary(self, backbone_configuration: Dict[str, Any],
                                          anchors_configuration: Dict[str, Any]) -> nn.ModuleDict:
        """
        Dynamically constructs the Region Proposal components tailored for each enhancer feature map scale.
        
        This builder method queries the Backbone for the exact spatial dimensions and channel depths 
        of the intermediate feature maps. It then parses the specified anchor configurations to securely 
        instantiate a distinct RegionProposal module for each scale level in the Feature Pyramid Network.
        
        Args:
            backbone_configuration (Dict[str, Any]): Configuration dictating backbone topology.
            anchors_configuration (Dict[str, Any]): Configuration governing anchor scales and aspect ratios
                                                    per feature level.
            
        Returns:
            nn.ModuleDict: A PyTorch ModuleDict mapping the stringified enhancer block indices to
                           their initialized RegionProposal modules.
        """
        region_proposer_dictionary = nn.ModuleDict()

        # First get the enhancer feature information, because they are used for the region proposals
        enhancer_input_information = self.backbone.compute_enhancer_input_information()

        # Iterate over the designated enhancer blocks and instantiate a RegionProposal for each multi-scale level
        for enhancer_index in backbone_configuration.get("enhancer_convolution_indices"):
            index_string = str(object=enhancer_index)

            # Retrieve the specific anchor scales and ratios for this scale level
            anchor_configuration = anchors_configuration.get("scales_and_ratios").get(index_string)
            scales = anchor_configuration.get("scales")
            aspect_ratios = anchor_configuration.get("aspect_ratios")

            # Dynamically fetch the accurate structural size and channel depth generated by the Backbone
            feature_map_size = enhancer_input_information[index_string]["feature_map_size"]
            input_channels = enhancer_input_information[index_string]["number_channels"]

            # Initialize and store the RegionProposal module
            region_proposer_dictionary[index_string] = RegionProposal(input_channels=input_channels,
                                                                      scales=scales,
                                                                      aspect_ratios=aspect_ratios,
                                                                      input_image_size=self.input_image_size,
                                                                      feature_map_size=feature_map_size,
                                                                      dtype=self.dtype,
                                                                      device=self.device)

        return region_proposer_dictionary

    def _build_region_proposal_filter(self, region_proposal_configuration: Dict[str, Any]) -> RegionProposalFilter:
        """
        Instantiates the RegionProposalFilter module to prune and refine bounding box proposals.
        
        This builder method provisions the filtering component with the NMS thresholds and bounding box 
        count limits explicitly tailored for the current execution mode (training vs. inference).
        
        Args:
            region_proposal_configuration (Dict[str, Any]): Configuration governing the region proposal thresholds.
            
        Returns:
            RegionProposalFilter: The initialized module for filtering bounding box proposals.
        """
        region_proposal_filter = RegionProposalFilter(configuration=region_proposal_configuration, mode=self.mode)

        return region_proposal_filter

    def aggregate_proposals_and_anchors(
            self,
            region_proposal_output_tensor_dictionary: Dict[str, Dict[str, torch.Tensor]]) -> Dict[str, torch.Tensor]:
        """
        Aggregates the multi-scale region proposals and their corresponding base anchors into a unified structure.

        This method iterates over the outputs from the various levels of the feature pyramid, concatenating the 
        classification scores, bounding box regressions, and proposal boxes along the sequence dimension. It also 
        retrieves the base anchors for each scale, expanding them to include a batch dimension to seamlessly align 
        with the network's batched predictions.

        Args:
            region_proposal_output_tensor_dictionary (Dict[str, Dict[str, torch.Tensor]]): A dictionary mapping enhancer 
            indices to their respective region proposal predictions.

        Returns:
            Dict[str, torch.Tensor]: A single dictionary containing the concatenated predictions
                                     and batched anchors across all scales.
                - "classification_scores" (torch.Tensor): Shape [batch_size, total_anchors]
                - "bounding_box_regressions" (torch.Tensor): Shape [batch_size, total_anchors, 4]
                - "proposal_boxes" (torch.Tensor): Shape [batch_size, total_anchors, 4]
                - "anchors" (torch.Tensor): Shape [batch_size, total_anchors, 4]
        """
        aggregated_scores = []
        aggregated_regressions = []
        aggregated_boxes = []
        aggregated_anchors = []

        for enhancer_index_string, predictions in region_proposal_output_tensor_dictionary.items():
            # Shape: [batch_size, anchors_per_scale]
            classification_scores = predictions["classification_scores"]

            # Shape: [batch_size, anchors_per_scale, 4]
            bounding_box_regressions = predictions["bounding_box_regressions"]

            # Shape: [batch_size, anchors_per_scale, 4]
            proposal_boxes = predictions["proposal_boxes"]

            batch_size = classification_scores.shape[0]

            # Fetch anchors and apply batch dimension expansion to match predictions
            # Base anchor shape: [anchors_per_scale, 4]
            anchors = self.region_proposer_dictionary[enhancer_index_string].region_proposal_anchor_object.anchors

            # Batched anchor shape: [batch_size, anchors_per_scale, 4]
            batched_anchors = anchors.unsqueeze(dim=0).expand(size=(batch_size, -1, 4))

            aggregated_scores.append(classification_scores)
            aggregated_regressions.append(bounding_box_regressions)
            aggregated_boxes.append(proposal_boxes)
            aggregated_anchors.append(batched_anchors)

        return {"classification_scores": torch.cat(tensors=aggregated_scores, dim=1),
                "bounding_box_regressions": torch.cat(tensors=aggregated_regressions, dim=1),
                "proposal_boxes": torch.cat(tensors=aggregated_boxes, dim=1),
                "anchors": torch.cat(tensors=aggregated_anchors, dim=1)}

    def forward(self, input_tensor: torch.Tensor,
                ground_truth_bounding_boxes: Optional[List[torch.Tensor]] = None) -> Dict[str, Any]:
        """
        Executes the forward pass of the Model.
        
        Args:
            input_tensor (torch.Tensor): The raw input image tensor.
            ground_truth_bounding_boxes (Optional[List[torch.Tensor]]): A list containing the ground truth boxes per image.
            
        Returns:
            Dict[str, Any]: A unified dictionary containing:
                - "final_backbone_tensor": The final backbone output tensor.
                - "backbone_output_tensor_dictionary": Enhancer indices to intermediate feature maps.
                - "region_proposal_output_tensor_dictionary": Predictions per enhancer scale.
                - "aggregated_proposals_dictionary": Flattened anchors and proposals across all scales.
                - "filtered_proposals_dictionary": The final filtered proposal boxes and their scores.
                - "batched_target_ground_truth_boxes" (if training): The matched ground truth boxes for each anchor.
                - "batched_labels" (if training): The foreground/background assignments for each anchor.
        """
        # Pass the raw image through the backbone to extract the multiscale feature maps
        final_backbone_tensor, backbone_output_tensor_dictionary = self.backbone(input_tensor=input_tensor)

        # Dictionary to store the output of the region proposal networks
        region_proposal_output_tensor_dictionary = {}

        for enhancer_index_string, feature_map_tensor in backbone_output_tensor_dictionary.items():
            # Pass the corresponding feature map through its specific region proposal block
            proposal_scores, proposal_boxes_transformations, proposal_boxes = self.region_proposer_dictionary[
                enhancer_index_string](input_tensor=feature_map_tensor)

            # Store the predictions structured securely by their enhancer indices
            region_proposal_output_tensor_dictionary[enhancer_index_string] = {
                "classification_scores": proposal_scores,
                "bounding_box_regressions": proposal_boxes_transformations,
                "proposal_boxes": proposal_boxes}

        # Aggregate the proposals and anchors across all scales for downstream processing
        # The resulting dictionary structure contains the following concatenated tensors:
        # - "classification_scores": The foreground probability scores for all anchors across all feature maps
        # - "bounding_box_regressions": The predicted coordinate offsets (dx, dy, dw, dh) for all anchors
        # - "proposal_boxes": The absolute [x_min, y_min, x_max, y_max] coordinates of the predicted proposals
        # - "anchors": The absolute [x_min, y_min, x_max, y_max] coordinates of the base anchors
        aggregated_proposals_dictionary = self.aggregate_proposals_and_anchors(
            region_proposal_output_tensor_dictionary=region_proposal_output_tensor_dictionary)

        # Refine the raw bounding box predictions by filtering out low scores and suppressing overlapping boxes
        filtered_boxes, filtered_scores = self.region_proposal_filter(
            proposal_boxes=aggregated_proposals_dictionary["proposal_boxes"],
            proposal_scores=aggregated_proposals_dictionary["classification_scores"],
            input_image_size=self.input_image_size)

        # Repackage the refined proposals cleanly into a dictionary structure
        filtered_proposals_dictionary = {"filtered_proposal_boxes": filtered_boxes,
                                         "filtered_proposal_scores": filtered_scores}


        # Package the outputs into a unified dictionary for clean extraction
        model_output_dictionary = {
            "final_backbone_tensor": final_backbone_tensor,
            "backbone_output_tensor_dictionary": backbone_output_tensor_dictionary,
            "region_proposal_output_tensor_dictionary": region_proposal_output_tensor_dictionary,
            "aggregated_proposals_dictionary": aggregated_proposals_dictionary,
            "filtered_proposals_dictionary": filtered_proposals_dictionary
        }

        # Depending on the mode:
        # Train -> Assign targets for loss computation
        if self.mode == "training" and ground_truth_bounding_boxes is not None:
            # First assign targets based on ground truth bounding boxes
            batched_target_ground_truth_boxes, batched_labels = batch_assign_targets_to_anchors(
                batched_ground_truth_boxes=ground_truth_bounding_boxes,
                batched_anchors=aggregated_proposals_dictionary["anchors"],
                background_iou_threshold=self.region_proposal_configuration['background_iou_threshold'],
                foreground_iou_threshold=self.region_proposal_configuration['foreground_iou_threshold'])
            
            # Append the assignments to the output dictionary
            model_output_dictionary["batched_target_ground_truth_boxes"] = batched_target_ground_truth_boxes
            model_output_dictionary["batched_labels"] = batched_labels

        return model_output_dictionary

    def print_summary(self) -> None:
        """
        Prints a structural summary of the overarching Model architecture.
        
        This method delegates to the underlying Backbone to print its layer-by-layer 
        spatial dimension summary, ensuring the structural integrity of the visual pipeline.
        """
        self.backbone.print_summary()
