import torch
from fiftyone.core.map.batcher import batch
from torch import nn
from rich.console import Console
from rich.panel import Panel
from typing import Dict, Any, Tuple, Literal, Optional, List
from architecture_modules.backbone import Backbone
from architecture_modules.region_proposer import RegionProposal, RegionProposalFilter
from architecture_modules.detector import DetectionHead
from utilities.model.model_utilities import assign_targets_to_anchors, batch_assign_targets_to_anchors, \
    turn_boxes_to_transformation_targets, apply_regression_predictions, sample_positive_and_negative_training_targets, \
    batch_assign_targets_to_proposals
from utilities.os_utilities import print_yellow
from utilities.tensor_utilities import print_tensor_shape, print_tensor_list, print_tensor_min_max


class Model(nn.Module):
    """
    Constructs the overall object detection model by combining the backbone,
    region proposal, and detector modules based on the configuration.
    """

    def __init__(self, configuration: Dict[str, Any], verbose: bool = False,
                 device: torch.device = None, dtype: torch.dtype = None) -> None:
        """
        Initializes the Model components.
        
        Args:
            configuration (Dict[str, Any]): The complete configuration dictionary for the experiment.
            verbose (bool): If True, prints a structural summary of the instantiated model architecture. Defaults to False.
            device (torch.device): The device for parameter allocation.
            dtype (torch.dtype): The data type for parameter allocation.
        """
        super(Model, self).__init__()

        # Assign device and dtype globally for the model
        self.device = device
        self.dtype = dtype
        self.verbose = verbose

        # Get configuration for each component of our model
        self.data_configuration = configuration.get('Data')
        self.backbone_configuration = configuration.get('Backbone')
        self.anchors_configuration = configuration.get('Anchors')
        self.region_proposal_configuration = configuration.get('RegionProposal')
        self.detector_configuration = configuration.get('Detector')

        # Get input image size and total number of classes
        self.input_image_size = self.data_configuration.get("image_settings").get("size")
        self.label_dictionary = self.data_configuration.get("label_dictionary")
        self.number_classes = len(self.label_dictionary)

        # Initialize the backbone feature extractor using the dedicated builder method
        self.backbone = self._build_backbone(backbone_configuration=self.backbone_configuration)

        # Pre-compute spatial dimensions and channel depths of the backbone's feature maps just once
        self.detection_input_information = self.backbone.compute_detection_input_information()

        # Initialize the region proposal dictionary (since we are using a Feature Pyramid Network Approach)
        self.region_proposer_dictionary = self._build_region_proposer_dictionary(
            region_proposal_configuration=self.region_proposal_configuration,
            anchors_configuration=self.anchors_configuration)

        # Initialize the detection head dictionary (each FPN scale gets its own detection head)
        self.detector_heads_dictionary = self._build_detector_heads_dictionary(
            detector_configuration=self.detector_configuration)

        # Aggregate all unbatched anchors across all scales into a single global tensor
        self.anchors = self._aggregate_all_anchors()
        self.number_anchors = self.anchors.shape[0]

        # Initialize the region proposal filter to refine the raw proposals generated by the network
        self.region_proposal_filter = self._build_region_proposal_filter(
            region_proposal_configuration=self.region_proposal_configuration)

    def _build_backbone(self, backbone_configuration: Dict[str, Any]) -> Backbone:
        """
        Instantiates the Backbone module based on the provided configuration blueprint.
        
        This builder method neatly encapsulates the construction of the visual feature 
        extractor, passing along the global structural parameters (like image size, 
        device, and precision type).
        
        Args:
            backbone_configuration (Dict[str, Any]): Configuration dictating the backbone topology and hyperparameters.
            
        Returns:
            Backbone: The fully initialized and configured feature extractor network.
        """
        backbone = Backbone(input_channels=backbone_configuration.get("input_channels"),
                            convolutions=backbone_configuration.get("convolutions"),
                            modules=backbone_configuration.get("modules"),
                            last_max_pooling=backbone_configuration.get("last_max_pooling"),
                            normalization=backbone_configuration.get("normalization"),
                            detection_convolution_block_indices=backbone_configuration.get(
                                "detection_convolution_block_indices"),
                            input_image_size=self.input_image_size,
                            device=self.device,
                            dtype=self.dtype)

        return backbone

    def _build_region_proposer_dictionary(self, region_proposal_configuration: Dict[str, Any],
                                          anchors_configuration: Dict[str, Any]) -> nn.ModuleDict:
        """
        Dynamically constructs the Region Proposal components tailored for each detection feature map scale.
        
        This builder method queries the Backbone for the exact spatial dimensions and channel depths 
        of the intermediate feature maps. It then parses the specified anchor configurations to securely 
        instantiate a distinct RegionProposal module for each scale level in the Feature Pyramid Network.
        
        Args:
            region_proposal_configuration (Dict[str, Any]): Configuration governing region proposal settings and normalization.
            anchors_configuration (Dict[str, Any]): Configuration governing anchor scales and aspect ratios
                                                    per feature level.
            
        Returns:
            nn.ModuleDict: A PyTorch ModuleDict mapping the stringified detection block indices to
                           their initialized RegionProposal modules.
        """
        region_proposer_dictionary = nn.ModuleDict()

        # Iterate over the sequentially ordered detection blocks computed by the backbone
        for index_string in self.detection_input_information.keys():
            # Retrieve the specific anchor scales and ratios for this scale level
            anchor_configuration = anchors_configuration.get("scales_and_ratios").get(index_string)
            scales = anchor_configuration.get("scales")
            aspect_ratios = anchor_configuration.get("aspect_ratios")

            # Dynamically fetch the accurate structural size and channel depth generated by the Backbone
            feature_map_size = self.detection_input_information[index_string]["feature_map_size"]
            input_channels = self.detection_input_information[index_string]["number_channels"]

            feature_map_normalization = self.region_proposal_configuration["normalization"]["feature_map_normalization"]
            # Initialize and store the RegionProposal module
            region_proposer_dictionary[index_string] = RegionProposal(
                head_configurations=self.region_proposal_configuration["head_configurations"][index_string],
                input_channels=input_channels,
                scales=scales,
                aspect_ratios=aspect_ratios,
                input_image_size=self.input_image_size,
                feature_map_size=feature_map_size,
                feature_map_normalization=feature_map_normalization,
                dtype=self.dtype,
                device=self.device)

        return region_proposer_dictionary

    def _build_detector_heads_dictionary(self, detector_configuration: Dict[str, Any]) -> nn.ModuleDict:
        """
        Dynamically constructs the Detection Head components tailored for each detection feature map scale.
        
        This builder method queries the Backbone for the exact spatial dimensions and channel depths 
        of the intermediate feature maps. It then parses the specified detector configurations to securely 
        instantiate a distinct DetectionHead module for each scale level in the Feature Pyramid Network.
        
        Args:
            detector_configuration (Dict[str, Any]): Configuration governing the detection heads
                                                     per feature level.
            
        Returns:
            nn.ModuleDict: A PyTorch ModuleDict mapping the stringified detection block indices to
                           their initialized DetectionHead modules.
        """
        detector_heads_dictionary = nn.ModuleDict()

        detector_head_configurations = detector_configuration.get("head_configurations")
        feature_map_normalization = detector_configuration.get("normalization").get("feature_map_normalization")

        # Iterate over the sequentially ordered detection blocks computed by the backbone
        for index_string in self.detection_input_information.keys():
            # Retrieve the specific head configuration for this scale level
            specific_configuration = detector_head_configurations.get(index_string)

            # Dynamically fetch the accurate structural size and channel depth generated by the Backbone
            feature_map_size = self.detection_input_information[index_string]["feature_map_size"]
            input_channels = self.detection_input_information[index_string]["number_channels"]

            # Initialize and store the DetectionHead module
            detector_heads_dictionary[index_string] = DetectionHead(detector_configuration=specific_configuration,
                                                                    number_classes=self.number_classes,
                                                                    input_channels=input_channels,
                                                                    feature_map_normalization=feature_map_normalization,
                                                                    input_image_size=self.input_image_size,
                                                                    feature_map_size=feature_map_size,
                                                                    dtype=self.dtype,
                                                                    device=self.device)

        return detector_heads_dictionary

    def _aggregate_all_anchors(self) -> torch.Tensor:
        """
        Aggregates the base unbatched anchors across all RegionProposal modules.
        
        This method concatenates the absolute base anchors from every scale level in the 
        Feature Pyramid Network into a single unified tensor. This provides easy global 
        access to all anchors via `model.anchors`.
        
        Returns:
            torch.Tensor: A tensor of shape [total_anchors, 4] containing all base bounding boxes.
        """
        aggregated_anchors = []

        # Iterate over all instanced RegionProposal modules and extract their base anchors
        for index_string, region_proposer in self.region_proposer_dictionary.items():
            aggregated_anchors.append(region_proposer.region_proposal_anchor_object.anchors)

        # Concatenate them vertically to form a single continuous list of bounding boxes
        return torch.cat(tensors=aggregated_anchors, dim=0)

    def _build_region_proposal_filter(self, region_proposal_configuration: Dict[str, Any]) -> RegionProposalFilter:
        """
        Instantiates the RegionProposalFilter module to prune and refine bounding box proposals.
        
        This builder method provisions the filtering component with the NMS thresholds and bounding box 
        count limits explicitly tailored for the current execution mode (training vs. inference).
        
        Args:
            region_proposal_configuration (Dict[str, Any]): Configuration governing the region proposal thresholds.
            
        Returns:
            RegionProposalFilter: The initialized module for filtering bounding box proposals.
        """
        region_proposal_filter = RegionProposalFilter(configuration=region_proposal_configuration, )

        return region_proposal_filter

    def aggregate_proposals_and_anchors(
            self,
            region_proposal_output_tensor_dictionary: Dict[str, Dict[str, torch.Tensor]]) -> Dict[str, torch.Tensor]:
        """
        Aggregates the multi-scale region proposals and batched anchors into a unified structure.

        This method iterates over the outputs from the various levels of the feature pyramid, concatenating the 
        classification scores, bounding box regressions, and proposal boxes along the sequence dimension. It leverages 
        the globally pre-aggregated `self.anchors` to construct the batched anchors efficiently in a single operation.

        Args:
            region_proposal_output_tensor_dictionary (Dict[str, Dict[str, torch.Tensor]]): A dictionary mapping detection 
            indices to their respective region proposal predictions.

        Returns:
            Dict[str, torch.Tensor]: A single dictionary containing the concatenated predictions
                                     and batched anchors across all scales.
                - "classification_scores" (torch.Tensor): Shape [batch_size, total_anchors]
                - "bounding_box_regressions" (torch.Tensor): Shape [batch_size, total_anchors, 4]
                - "proposal_boxes" (torch.Tensor): Shape [batch_size, total_anchors, 4]
                - "anchors" (torch.Tensor): Shape [batch_size, total_anchors, 4]
                - "convolution_block_origin" (torch.Tensor): Shape [batch_size, total_anchors]
        """
        aggregated_scores = []
        aggregated_regressions = []
        aggregated_boxes = []
        aggregated_origins = []

        batch_size = None

        for detection_index_string, predictions in region_proposal_output_tensor_dictionary.items():
            # Shape: [batch_size, anchors_per_scale]
            classification_scores = predictions["classification_scores"]

            # Shape: [batch_size, anchors_per_scale, 4]
            bounding_box_regressions = predictions["bounding_box_regressions"]

            # Shape: [batch_size, anchors_per_scale, 4]
            proposal_boxes = predictions["proposal_boxes"]

            if batch_size is None:
                batch_size = classification_scores.shape[0]

            # Generate origin tracker to know which FPN level these proposals came from
            origin_tensor = torch.full_like(input=classification_scores, fill_value=int(detection_index_string),
                                            dtype=torch.int64)

            aggregated_scores.append(classification_scores)
            aggregated_regressions.append(bounding_box_regressions)
            aggregated_boxes.append(proposal_boxes)
            aggregated_origins.append(origin_tensor)

        return {"classification_scores": torch.cat(tensors=aggregated_scores, dim=1),
                "bounding_box_regressions": torch.cat(tensors=aggregated_regressions, dim=1),
                "proposal_boxes": torch.cat(tensors=aggregated_boxes, dim=1),
                "convolution_block_origin": torch.cat(tensors=aggregated_origins, dim=1),
                # Batched anchor shape: [batch_size, anchors_per_scale, 4]
                "anchors": self.anchors.unsqueeze(dim=0).expand(size=(batch_size, -1, 4))}

    def aggregate_detection_outputs(self,
                                    detection_output_dictionary: Dict[str, Dict[str, Optional[torch.Tensor]]]
                                    ) -> Dict[str, Optional[torch.Tensor]]:
        """
        Aggregates the multi-scale detection outputs into a unified structure.

        This method iterates over the detection outputs from the various levels of the feature pyramid, 
        concatenating the classification scores, bounding box regressions, and corresponding sliced 
        targets (if in training mode) along the first dimension (total proposals across all scales).

        Args:
            detection_output_dictionary (Dict[str, Dict[str, Optional[torch.Tensor]]]): A dictionary mapping detection 
            indices to their respective detection head predictions and sliced targets.

        Returns:
            Dict[str, Optional[torch.Tensor]]: A single dictionary containing the concatenated predictions
                                               and targets across all scales.
                - "classification_scores" (torch.Tensor): Shape [total_proposals, number_classes]
                - "box_regressions" (torch.Tensor): Shape [total_proposals, number_classes, 4]
                - "sliced_proposals" (torch.Tensor): Shape [total_proposals, 5]
                - "sliced_batch_indices" (torch.Tensor): Shape [total_proposals, 1]
                - "detection_boxes" (Optional[torch.Tensor]): Shape [total_proposals, number_classes, 4]
                - "sliced_labels" (Optional[torch.Tensor]): Shape [total_proposals] (only in training)
                - "sliced_regression_targets" (Optional[torch.Tensor]): Shape [total_proposals, 4] (only in training)
        """
        aggregated_scores = []
        aggregated_regressions = []
        aggregated_labels = []
        aggregated_regression_targets = []
        aggregated_proposals = []
        aggregated_detection_boxes = []
        aggregated_batch_indices = []

        for detection_index_string, predictions in detection_output_dictionary.items():
            aggregated_scores.append(predictions["classification_scores"])
            aggregated_regressions.append(predictions["box_regressions"])
            aggregated_proposals.append(predictions["sliced_proposals"])
            aggregated_batch_indices.append(predictions["sliced_batch_indices"])
            aggregated_detection_boxes.append(predictions["detection_boxes"])

            if self.training:
                aggregated_labels.append(predictions["sliced_labels"])
                aggregated_regression_targets.append(predictions["sliced_regression_targets"])

        return {
            "classification_scores": torch.cat(tensors=aggregated_scores, dim=0),
            "box_regressions": torch.cat(tensors=aggregated_regressions, dim=0),
            "detection_boxes": torch.cat(tensors=aggregated_detection_boxes, dim=0),
            "sliced_batch_indices": torch.cat(tensors=aggregated_batch_indices, dim=0),
            "sliced_proposals": torch.cat(tensors=aggregated_proposals, dim=0),
            "sliced_labels": torch.cat(tensors=aggregated_labels, dim=0) if self.training else None,
            "sliced_regression_targets": torch.cat(tensors=aggregated_regression_targets,
                                                   dim=0) if self.training else None}

    def _rearrange_predictions_by_batch(self, batch_size: int, detection_batch_indices: torch.Tensor,
                                        prediction_tensors_dictionary: Dict[str, Optional[torch.Tensor]],
                                        verbose: bool = False,
                                        ) -> Dict[str, Optional[torch.Tensor]]:
        """
        Re-arranges the flattened network predictions back into a batched list format.
        
        This method groups the predicted class scores, box regressions, and final bounding 
        boxes by their original batch index. This is particularly useful during inference 
        or metric calculation, where predictions need to be associated with their specific 
        input images.
        
        Args:
            batch_size (int): The total number of images in the batch.
            detection_batch_indices (torch.Tensor): The batch indices mapping each proposal to an image. Shape: [K, 1] or [K].
            prediction_tensors_dictionary (Dict[str, Optional[torch.Tensor]]): A dictionary containing 
                                            the flattened prediction tensors (e.g., classification_scores, detection_boxes).
                                            Each valid tensor must have a first dimension of size K.
            verbose (bool): If True, prints a structural summary of the resulting rearranged tensors. Defaults to False.
                                            
        Returns:
            Dict[str, Optional[torch.Tensor]]: A dictionary where each key maps to a batched tensor of shape `[batch_size, ...]`, 
                                           containing the predictions for each specific image.
        """

        tensor_names = ["classification_scores", "box_regressions", "detection_boxes"]
        rearranged_predictions = {key: [] for key in tensor_names}

        # Squeeze the indices since they are of shape [K, 1]
        squeezed_indices = detection_batch_indices.squeeze(dim=-1)

        for batch_index in range(batch_size):
            # Find the indices of the proposals that belong to the current image
            image_indices = torch.where(squeezed_indices == batch_index)[0]

            for tensor_name, tensor_data in prediction_tensors_dictionary.items():
                if tensor_data is not None and tensor_name in tensor_names:
                    rearranged_predictions[tensor_name].append(tensor_data[image_indices])

        # Stack the lists into batched tensors
        for tensor_name, tensor_list in rearranged_predictions.items():
            if tensor_list is not None and len(tensor_list) > 0:
                rearranged_predictions[tensor_name] = torch.stack(tensors=tensor_list, dim=0)

        if verbose:
            print_yellow(f"Re-Arranged Detection Output Information", add_separators=True)
            for tensor_name, tensor_value in rearranged_predictions.items():
                print_tensor_shape(tensor_value, tensor_name, indent=1)

        return rearranged_predictions

    def _compute_region_proposal_losses(self, ground_truth_bounding_boxes: List[torch.Tensor],
                                        aggregated_proposals_dictionary: Dict[str, torch.Tensor]) -> Tuple[
        torch.Tensor, torch.Tensor]:
        """
        Computes the Region Proposal Network classification and localisation losses.

        This isolated logic extracts positive and negative target anchors, compares the predicted
        logits and regressed box offsets against the true targets, and generates the two loss
        components used to train the region proposer.

        Args:
            ground_truth_bounding_boxes (List[torch.Tensor]): The batched ground truth boxes.
            aggregated_proposals_dictionary (Dict[str, torch.Tensor]): The aggregated anchor and prediction tensor.

        Returns:
            Tuple[torch.Tensor, torch.Tensor]: The scalar classification loss and localisation loss.
        """

        # First assign targets based on ground truth bounding boxes
        # Here we consider absolutely all anchors targets based on all ground truth boxes
        region_proposal_anchor_targets, region_proposal_anchor_labels = batch_assign_targets_to_anchors(
            batched_ground_truth_boxes=ground_truth_bounding_boxes,
            batched_anchors=aggregated_proposals_dictionary["anchors"],
            background_iou_threshold=self.region_proposal_configuration['background_iou_threshold'],
            foreground_iou_threshold=self.region_proposal_configuration['foreground_iou_threshold'],
            strict_fallback_assignment=self.region_proposal_configuration['strict_fallback_assignment'])

        # Compute region proposal regression targets
        region_proposal_regression_targets = turn_boxes_to_transformation_targets(
            ground_truth_boxes=region_proposal_anchor_targets,
            predicted_boxes=aggregated_proposals_dictionary["anchors"])

        # Get training samples for region proposal network
        sampled_positive_mask, sampled_negative_mask = sample_positive_and_negative_training_targets(
            labels=region_proposal_anchor_labels,
            desired_positives=self.region_proposal_configuration['number_training_positives'],
            desired_total=self.region_proposal_configuration['total_training_samples'])

        # Compute the classification loss: Simple binary cross entropy loss
        # We use the variant 'with_logits' since the classification scores are raw, un-sigmoid network outputs.
        # Computed over both the sampled positive (foreground) and sampled negative (background) anchors.
        sampled_mask = sampled_positive_mask | sampled_negative_mask

        region_proposal_classification_loss = torch.nn.functional.binary_cross_entropy_with_logits(
            input=aggregated_proposals_dictionary["classification_scores"][sampled_mask],
            target=region_proposal_anchor_labels[sampled_mask],
            reduction="mean")

        # Compute the localization loss: Smooth L1 Loss (Huber Loss)
        # We only compute regression loss on the positively sampled anchors, as background anchors have no target.
        # We explicitly use reduction="sum" and divide by the total number of positive anchors instead of using
        # reduction="mean". This ensures the loss is averaged per bounding box rather than per individual
        # coordinate, aligning perfectly with standard Region Proposal Network normalization practices.
        region_proposal_localisation_loss = torch.nn.functional.smooth_l1_loss(
            input=aggregated_proposals_dictionary["bounding_box_regressions"][sampled_positive_mask],
            target=region_proposal_regression_targets[sampled_positive_mask],
            beta=self.region_proposal_configuration['localisation_loss_beta'],
            reduction="sum") / torch.sum(input=sampled_positive_mask)

        return region_proposal_classification_loss, region_proposal_localisation_loss

    def _compute_detection_losses(self, aggregated_detections_dictionary: Dict[str, Optional[torch.Tensor]]) -> Tuple[
        torch.Tensor, torch.Tensor]:
        """
        Computes the final Detection Head classification and localisation losses.

        Args:
            aggregated_detections_dictionary (Dict[str, Optional[torch.Tensor]]): The aggregated predictions 
                                                                                 and targets from all detection heads.
                - "classification_scores" (torch.Tensor): Shape [total_proposals, number_classes]
                - "box_regressions" (torch.Tensor): Shape [total_proposals, number_classes, 4]
                - "sliced_proposals" (torch.Tensor): Shape [total_proposals, 5]
                - "sliced_labels" (torch.Tensor): Shape [total_proposals]
                - "sliced_regression_targets" (torch.Tensor): Shape [total_proposals, 4]

        Returns:
            Tuple[torch.Tensor, torch.Tensor]: The classification loss and the bounding box regression loss (scalar tensors).
        """
        # Compute the Classification Loss (Cross Entropy)
        # This evaluates all sampled proposals (both foreground and background). 
        # The background proposals (label 0) will naturally train the network to suppress false positives.
        detection_classification_loss = torch.nn.functional.cross_entropy(
            input=aggregated_detections_dictionary["classification_scores"],
            target=aggregated_detections_dictionary["sliced_labels"])

        # Filter out background proposals: Bounding box regressions are ONLY trained on positive, foreground samples.
        sampled_positive_indices = torch.where(aggregated_detections_dictionary["sliced_labels"] > 0)[0]
        foreground_classes = aggregated_detections_dictionary["sliced_labels"][sampled_positive_indices].long()

        # Compute the Localisation Loss (Smooth L1 / Huber Loss)
        # The detector outputs regression predictions for EVERY class [K, number_classes, 4]. 
        # We use advanced indexing `[sampled_positive_indices, foreground_classes]` to pluck out ONLY the 4 
        # coordinate regressions that correspond to the specific ground truth class of each proposal.
        detection_localisation_loss = torch.nn.functional.smooth_l1_loss(
            input=aggregated_detections_dictionary["box_regressions"][sampled_positive_indices, foreground_classes],
            target=aggregated_detections_dictionary["sliced_regression_targets"][sampled_positive_indices],
            beta=self.detector_configuration['localisation_loss_beta'],
            reduction="sum") / max(1, sampled_positive_indices.numel())

        return detection_classification_loss, detection_localisation_loss

    def _prepare_detector_inputs(self,
                                 filtered_boxes: torch.Tensor,
                                 filtered_origins: torch.Tensor,
                                 ground_truth_bounding_boxes: Optional[List[torch.Tensor]] = None,
                                 ground_truth_labels: Optional[List[torch.Tensor]] = None,
                                 verbose: bool = False
                                 ) -> Tuple[
        torch.Tensor, torch.Tensor, Optional[torch.Tensor], Optional[torch.Tensor], torch.Tensor]:
        """
        Prepares the formatted inputs required by the Detection Head's RoIAlign and loss functions.
        
        During training, it assigns ground truth targets to the filtered proposals, computes regression
        targets, and samples a balanced set of positive and negative proposals.
        During inference, it simply flattens the filtered proposals and prepends batch indices.
        
        Args:
            filtered_boxes (torch.Tensor): The filtered region proposals of shape [Batch, Num_Proposals, 4].
            filtered_origins (torch.Tensor): The detection scale origins of the proposals of shape [Batch, Num_Proposals].
            ground_truth_bounding_boxes (Optional[List[torch.Tensor]]): List of ground truth bounding boxes.
            ground_truth_labels (Optional[List[torch.Tensor]]): List of ground truth class labels.
            verbose (bool): If True, prints a structural summary of the generated inputs. Defaults to False.
            
        Returns:
            Tuple containing:
                - detection_proposals (torch.Tensor): Formatted proposals of shape [K, 5] (batch_index + coords).
                - detection_proposals_origins (torch.Tensor): Origins of shape [K].
                - detection_labels (Optional[torch.Tensor]): Assigned ground truth labels of shape [K].
                - detection_regression_targets (Optional[torch.Tensor]): Target regressions of shape [K, 4].
                - detection_batch_indices (torch.Tensor): The batch indices for each valid proposal of shape [K, 1].
        """
        batch_size, num_proposals, _ = filtered_boxes.shape

        # Generate batch indices of shape [Batch, Proposals] to track which image each proposal belongs to
        batch_indices = torch.arange(start=0, end=batch_size, device=self.device,
                                     dtype=self.dtype).view(-1, 1).expand(batch_size, num_proposals)

        if self.training and ground_truth_bounding_boxes is not None:
            # First assign targets based on ground truth bounding boxes
            # Here we consider only the filtered proposal boxes from the NMS based on all ground truth boxes
            # TODO Find out if this is the right approach.
            detector_proposal_targets, detector_proposal_labels = batch_assign_targets_to_proposals(
                batched_ground_truth_boxes=ground_truth_bounding_boxes,
                batched_proposals=filtered_boxes,
                batched_ground_truth_labels=ground_truth_labels,
                foreground_iou_threshold=self.detector_configuration["foreground_iou_threshold"])

            # Compute detection head regression targets
            detection_regression_targets = turn_boxes_to_transformation_targets(
                ground_truth_boxes=detector_proposal_targets,
                predicted_boxes=filtered_boxes)

            # Get training samples for detection network
            sampled_positive_mask, sampled_negative_mask = sample_positive_and_negative_training_targets(
                labels=detector_proposal_labels,
                desired_positives=self.detector_configuration['number_training_positives'],
                desired_total=self.detector_configuration['total_training_samples'],
                verbose=self.verbose)

            sampled_mask = sampled_positive_mask | sampled_negative_mask

            # Apply the mask, extracting only the valid elements across the entire batch (flattening them)
            detection_batch_indices = batch_indices[sampled_mask].unsqueeze(dim=-1)
            sampled_boxes = filtered_boxes[sampled_mask]

            # Concatenate the batch indices as the first column to create the [K, 5] tensor expected by RoIAlign
            detection_proposals = torch.cat(tensors=[detection_batch_indices, sampled_boxes], dim=-1)
            detection_proposals_origins = filtered_origins[sampled_mask]

            detection_labels = detector_proposal_labels[sampled_mask]
            detection_regression_targets = detection_regression_targets[sampled_mask]

        else:
            # During inference, simply flatten the valid proposals and prepend the batch indices
            detection_batch_indices = batch_indices.reshape(-1).unsqueeze(dim=-1)
            flattened_boxes = filtered_boxes.reshape(-1, 4)

            detection_proposals = torch.cat(tensors=[detection_batch_indices, flattened_boxes], dim=-1)
            detection_proposals_origins = filtered_origins.reshape(-1)

            detection_labels = None
            detection_regression_targets = None

        # Calculate and display the final breakdown detection input proposals for debugging
        if verbose:
            print_yellow("Detector Information", add_separators=True)
            print_tensor_shape(detection_proposals, indent=1)
            print_tensor_shape(detection_proposals_origins, indent=1)
            if self.training:
                print_tensor_shape(detection_labels, indent=1)
                print_tensor_shape(detection_regression_targets, indent=1)

        return (detection_proposals, detection_proposals_origins, detection_labels, detection_regression_targets,
                detection_batch_indices)

    def _forward_region_proposals(
            self, backbone_output_tensor_dictionary: Dict[str, torch.Tensor]) -> Dict[str, Dict[str, torch.Tensor]]:
        """
        Executes the Region Proposal forward pass for all intermediate feature map scales.
        
        Args:
            backbone_output_tensor_dictionary (Dict[str, torch.Tensor]): The multi-scale backbone feature maps of shape [Batch, Channels, Height, Width].
            
        Returns:
            Dict[str, Dict[str, torch.Tensor]]: The predicted proposal scores, bounding box regressions, 
                                                and generated proposal boxes per detection block index.
                - "classification_scores" (torch.Tensor): Shape [Batch, Anchors_in_scale]
                - "bounding_box_regressions" (torch.Tensor): Shape [Batch, Anchors_in_scale, 4]
                - "proposal_boxes" (torch.Tensor): Shape [Batch, Anchors_in_scale, 4]
        """
        region_proposal_output_tensor_dictionary = {}

        for detection_index_string, feature_map_tensor in backbone_output_tensor_dictionary.items():
            # Pass the corresponding feature map through its specific region proposal block
            proposal_scores, proposal_boxes_transformations, proposal_boxes = self.region_proposer_dictionary[
                detection_index_string](input_tensor=feature_map_tensor)

            # Store the predictions structured securely by their detection indices
            region_proposal_output_tensor_dictionary[detection_index_string] = {
                "classification_scores": proposal_scores,
                "bounding_box_regressions": proposal_boxes_transformations,
                "proposal_boxes": proposal_boxes}

        return region_proposal_output_tensor_dictionary

    def _forward_detections(
            self,
            backbone_output_tensor_dictionary: Dict[str, torch.Tensor],
            detection_proposals: torch.Tensor,
            detection_proposals_origins: torch.Tensor,
            detection_batch_indices: torch.Tensor,
            detection_labels: Optional[torch.Tensor] = None,
            detection_regression_targets: Optional[torch.Tensor] = None
    ) -> Dict[str, Any]:
        """
        Executes the Detection Head forward pass for all proposals across their respective feature maps.
        
        Args:
            backbone_output_tensor_dictionary (Dict[str, torch.Tensor]): The multi-scale backbone feature maps of shape [Batch, Channels, Height, Width].
            detection_proposals (torch.Tensor): Formatted proposals of shape [K, 5] (batch_index + coords).
            detection_proposals_origins (torch.Tensor): Origins of shape [K].
            detection_batch_indices (torch.Tensor): Batch indices of shape [K, 1].
            detection_labels (Optional[torch.Tensor]): Target labels for training of shape [K].
            detection_regression_targets (Optional[torch.Tensor]): Target regressions for training of shape [K, 4].
            
        Returns:
            Dict[str, Any]: Dictionary mapping detection index to a dictionary containing the sliced and computed outputs:
                - "classification_scores" (torch.Tensor): Shape [K_scale, number_classes]
                - "box_regressions" (torch.Tensor): Shape [K_scale, number_classes, 4]
                - "sliced_labels" (Optional[torch.Tensor]): Shape [K_scale]
                - "sliced_regression_targets" (Optional[torch.Tensor]): Shape [K_scale, 4]
                - "sliced_proposals" (torch.Tensor): Shape [K_scale, 5]
        """
        detection_output_dictionary = {}

        for detection_index_string, feature_map_tensor in backbone_output_tensor_dictionary.items():
            # Find the indices of the proposals that originated from this specific feature map scale
            scale_indices = torch.where(detection_proposals_origins == int(detection_index_string))[0]

            # Slice the valid proposals for this particular scale
            scale_proposals = detection_proposals[scale_indices]
            scale_batch_indices = detection_batch_indices[scale_indices]

            # Slice the labels and regression targets if they are provided (training mode)
            scale_labels = detection_labels[scale_indices] if detection_labels is not None else None
            scale_regression_targets = detection_regression_targets[
                scale_indices] if detection_regression_targets is not None else None

            # Retrieve the specific detection head for this feature map scale
            detection_head = self.detector_heads_dictionary[detection_index_string]

            # Execute the forward pass to get the classification logits and bounding box regressions
            classification_scores, box_regressions, detection_boxes = detection_head(proposal_boxes=scale_proposals,
                                                                                     input_tensor=feature_map_tensor)

            # Store the computed tensors and the sliced ground truth targets for later loss computation
            detection_output_dictionary[detection_index_string] = {
                "classification_scores": classification_scores,
                "box_regressions": box_regressions,
                "detection_boxes": detection_boxes,
                "sliced_batch_indices": scale_batch_indices,
                "sliced_labels": scale_labels,
                "sliced_regression_targets": scale_regression_targets,
                "sliced_proposals": scale_proposals}

        return detection_output_dictionary

    def forward(self, input_tensor: torch.Tensor,
                ground_truth_bounding_boxes: Optional[List[torch.Tensor]] = None,
                ground_truth_labels: Optional[List[torch.Tensor]] = None, ) -> Dict[str, Any]:
        """
        Executes the forward pass of the Model.
        
        Args:
            input_tensor (torch.Tensor): The raw input image tensor of shape [Batch, Channels, Height, Width].
            ground_truth_bounding_boxes (Optional[List[torch.Tensor]]): List containing ground truth boxes per image, each of shape [Num_GT, 4].
            ground_truth_labels (Optional[List[torch.Tensor]]): List containing ground truth labels per image, each of shape [Num_GT].
            
        Returns:
            Dict[str, Any]: A unified dictionary containing:
                - "classification_scores" (torch.Tensor): Shape [Batch, Post_NMS_Proposals, number_classes].
                - "box_regressions" (torch.Tensor): Shape [Batch, Post_NMS_Proposals, number_classes, 4].
                - "detection_boxes" (torch.Tensor): Shape [Batch, Post_NMS_Proposals, number_classes, 4].
                - "region_proposal_classification_loss" (Optional[torch.Tensor]): Scalar loss (if training).
                - "region_proposal_localisation_loss" (Optional[torch.Tensor]): Scalar loss (if training).
                - "detection_classification_loss" (Optional[torch.Tensor]): Scalar loss (if training).
                - "detection_regression_loss" (Optional[torch.Tensor]): Scalar loss (if training).
        """
        # Pass the raw image through the backbone to extract the multiscale feature maps
        final_backbone_tensor, backbone_output_tensor_dictionary = self.backbone(input_tensor=input_tensor)

        # Execute the Region Proposal networks across all extracted intermediate feature maps
        region_proposal_output_tensor_dictionary = self._forward_region_proposals(
            backbone_output_tensor_dictionary=backbone_output_tensor_dictionary)

        # Aggregate the proposals and anchors across all scales for downstream processing
        # The resulting dictionary structure contains the following concatenated tensors:
        # - "classification_scores": The foreground probability scores for all anchors across all feature maps
        # - "bounding_box_regressions": The predicted coordinate offsets (dx, dy, dw, dh) for all anchors
        # - "proposal_boxes": The absolute [x_min, y_min, x_max, y_max] coordinates of the predicted proposals
        # - "anchors": The absolute [x_min, y_min, x_max, y_max] coordinates of the base anchors
        aggregated_proposals_dictionary = self.aggregate_proposals_and_anchors(
            region_proposal_output_tensor_dictionary=region_proposal_output_tensor_dictionary)

        # Refine the raw bounding box predictions by filtering out low scores and suppressing overlapping boxes
        filtered_boxes, filtered_scores, filtered_origins = self.region_proposal_filter(
            proposal_boxes=aggregated_proposals_dictionary["proposal_boxes"],
            proposal_scores=aggregated_proposals_dictionary["classification_scores"],
            proposal_origins=aggregated_proposals_dictionary["convolution_block_origin"],
            input_image_size=self.input_image_size)

        # Prepare the filtered proposals to be safely digested by the Detection Head's RoIAlign
        (detection_proposals, detection_proposals_origins,
         detection_labels, detection_regression_targets,
         detection_batch_indices) = self._prepare_detector_inputs(
            filtered_boxes=filtered_boxes,
            filtered_origins=filtered_origins,
            ground_truth_bounding_boxes=ground_truth_bounding_boxes,
            ground_truth_labels=ground_truth_labels,
            verbose=self.verbose)

        # Route the formatted proposals to their appropriate detection heads to compute final box scores and regressions
        detection_output_tensor_dictionary = self._forward_detections(
            backbone_output_tensor_dictionary=backbone_output_tensor_dictionary,
            detection_proposals=detection_proposals,
            detection_proposals_origins=detection_proposals_origins,
            detection_batch_indices=detection_batch_indices,
            detection_labels=detection_labels,
            detection_regression_targets=detection_regression_targets)

        # Aggregate the final detection head outputs across all scales
        aggregated_detections_dictionary = self.aggregate_detection_outputs(
            detection_output_dictionary=detection_output_tensor_dictionary)

        # Package the outputs into a unified dictionary for clean extraction
        # Rearrange the flattened detections back into a batched list format
        model_output_dictionary = self._rearrange_predictions_by_batch(
            batch_size=input_tensor.shape[0],
            detection_batch_indices=aggregated_detections_dictionary["sliced_batch_indices"],
            prediction_tensors_dictionary=aggregated_detections_dictionary,
            verbose=self.verbose)

        # Train -> Loss Computation :
        # - For Region Proposal
        # - For Detection
        if self.training and ground_truth_bounding_boxes is not None:
            # Region Proposal Losses
            (region_proposal_classification_loss,
             region_proposal_localisation_loss) = self._compute_region_proposal_losses(
                ground_truth_bounding_boxes=ground_truth_bounding_boxes,
                aggregated_proposals_dictionary=aggregated_proposals_dictionary)

            # Detection Losses
            (detection_classification_loss, detection_regression_loss) = self._compute_detection_losses(
                aggregated_detections_dictionary=aggregated_detections_dictionary)

            # todo Consider adding the ground truth bounding boxes as well ?
            #  so that the network also learns not to modify some boxes ?
            #  would be easy to implement since we would be using lists ?

            # Append the assignments to the output dictionary
            model_output_dictionary["region_proposal_classification_loss"] = region_proposal_classification_loss
            model_output_dictionary["region_proposal_localisation_loss"] = region_proposal_localisation_loss

            model_output_dictionary["detection_classification_loss"] = detection_classification_loss
            model_output_dictionary["detection_regression_loss"] = detection_regression_loss

        return model_output_dictionary

    def print_summary(self) -> None:
        """
        Prints a structural summary of the overarching Model architecture.
        
        This method delegates to the underlying Backbone to print its layer-by-layer 
        spatial dimension summary, then prints the Region Proposal summary, and finally 
        the Detection summary, ensuring the structural integrity of the visual pipeline.
        """
        self.backbone.print_summary()
        self.print_region_proposal_summary()
        self.print_detection_summary()

    def print_region_proposal_summary(self) -> None:
        """
        Prints a structural summary of the Region Proposal Network components.
        
        This summary leverages rich panels to cleanly display the feature map size, the number 
        of scales, aspect ratios, and the absolute anchor count for each configured RPN block, 
        culminating in the total number of region proposal anchors across the entire network.
        """
        console = Console(width=60)

        summary_text = ""

        for index_string, region_proposal_object in self.region_proposer_dictionary.items():
            # Feature map spatial size
            feature_map_size = region_proposal_object.feature_map_size

            # Anchor scales and ratios
            scales = region_proposal_object.scales
            aspect_ratios = region_proposal_object.aspect_ratios
            number_of_anchors_per_location = region_proposal_object.number_anchors_per_location

            # Calculate the total number of region proposal anchors generated by this specific block by multiplying
            # the spatial area of the feature map by the number of anchors spawned at each spatial location
            total_anchors_for_proposal = feature_map_size * feature_map_size * number_of_anchors_per_location

            summary_text += f"[bold]Convolution Block {index_string}[/bold]\n"
            summary_text += f"  - Feature Map Size : [{feature_map_size}, {feature_map_size}]\n"
            summary_text += f"  - Scales           : {scales}\n"
            summary_text += f"  - Aspect Ratios    : {aspect_ratios}\n"
            summary_text += f"  - Total Anchors    : {total_anchors_for_proposal}\n\n"

        summary_text += f"[bold blue]Total Network Anchors: {self.number_anchors}[/bold blue]"

        panel = Panel(summary_text, title="[bold]Region Proposal Architecture[/bold]", border_style="yellow")
        console.print(panel)

    def print_detection_summary(self) -> None:
        """
        Prints a structural summary of the Detection Network components.
        
        This summary leverages rich panels to cleanly display the feature map size, the RoI Align 
        pool size, and the spatial scale used for RoI pooling across each configured Detection block.
        """
        console = Console(width=60)

        # Initialize the textual representation of the architecture,
        # including the applied normalization strategy prominently
        summary_text = (f"[bold]Normalization Strategy:[/bold]"
                        f" {str(object=self.detector_configuration["normalization"]["feature_map_normalization"]).capitalize()}\n\n")

        for index_string, detection_head in self.detector_heads_dictionary.items():
            convolution_layers = detection_head.convolution_number_layers
            fully_connected_layers = detection_head.fully_connected_dimensions
            feature_map_size = detection_head.feature_map_size
            roi_align_pool_size = detection_head.roi_align_pool_size
            spatial_scale = detection_head.spatial_scale

            summary_text += f"[bold]Detection Block {index_string}[/bold]\n"
            summary_text += f"  - Convolution Layers : {convolution_layers}\n"
            summary_text += f"  - Fully Conn. Layers : {fully_connected_layers}\n"
            summary_text += f"  - Feature Map Size   : [{feature_map_size}, {feature_map_size}]\n"
            summary_text += f"  - RoI Align Pool     : [{roi_align_pool_size}, {roi_align_pool_size}]\n"
            summary_text += f"  - Spatial Scale      : {spatial_scale:.4f}\n\n"

        if summary_text.endswith("\n\n"):
            summary_text = summary_text[:-2]

        panel = Panel(summary_text, title="[bold]Detection Architecture[/bold]", border_style="green")
        console.print(panel)
